# Generated by Django 3.0 on 2022-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CognateWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_cognate_word', models.CharField(max_length=50)),
                ('ru_cognate_word', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['en_cognate_word'],
            },
        ),
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_collocation', models.CharField(max_length=50)),
                ('ru_collocation', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['en_collocation'],
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['part_of_speech'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_phrase', models.CharField(max_length=50)),
                ('ru_phrase', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['en_phrase'],
            },
        ),
        migrations.CreateModel(
            name='RuWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='EnWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('audio_us', models.FileField(blank=True, upload_to='audio/')),
                ('audio_uk', models.FileField(blank=True, upload_to='audio/')),
                ('cognate_word', models.ManyToManyField(to='vocab.CognateWord')),
                ('collocation', models.ManyToManyField(blank=True, to='vocab.Collocation')),
                ('part_of_speech', models.ManyToManyField(blank=True, to='vocab.PartOfSpeech')),
                ('phrase', models.ManyToManyField(blank=True, to='vocab.Phrase')),
                ('translate', models.ManyToManyField(blank=True, to='vocab.RuWord')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
