# Generated by Django 3.0 on 2022-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_auto_20220121_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cognateword',
            name='ru_cognate_word',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collocation',
            name='ru_collocation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partofspeech',
            name='part_of_speech',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='ru_phrase',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ruword',
            name='word',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
